#!/usr/bin/env bash

# ==============================================================================
# Configuration
# ==============================================================================

# S4 image generated by generator/main.py
S4IMG_FILE="./bin/s4_image.bin"

# The target UEFI application built by 'build_uefi.sh'
EFI_FILE="./bin/Activator.efi"

# Bhyve specific settings
VM_NAME="s4_activator_test"
DISK_IMG="./bin/bhyve_disk.img"

# Standard location for the EDK2 firmware package on FreeBSD
BHYVE_FW="/usr/local/share/uefi-firmware/BHYVE_UEFI.fd"

# ==============================================================================
# Pre-flight Checks
# ==============================================================================

# 1. Check for Root (Bhyve requires root)
if [ "$(id -u)" -ne 0 ]; then
    echo "Error: Bhyve requires root privileges. Please run with sudo."
    exit 1
fi

# 2. Check Dependencies
if ! command -v bhyve &> /dev/null; then
    echo "Error: 'bhyve' not found. Is the base system installed correctly?"
    exit 1
fi

# We use mtools to create the FAT image without mounting it (cleaner/safer)
if ! command -v mcopy &> /dev/null; then
    echo "Error: 'mtools' not found."
    echo "Please install it: pkg install mtools"
    exit 1
fi

# 3. Check Firmware
if [ ! -f "$BHYVE_FW" ]; then
    echo "Error: Bhyve UEFI firmware not found at $BHYVE_FW"
    echo "Please install the edk2 firmware: pkg install edk2"
    exit 1
fi

# 4. Check Artifacts
if [ ! -f "$S4IMG_FILE" ]; then
    echo "Error: Binary not found at $S4IMG_FILE"
    echo "Please run 'python3 generator/main.py' first."
    exit 1
fi

if [ ! -f "$EFI_FILE" ]; then
    echo "Error: Binary not found at $EFI_FILE"
    echo "Please run './scripts/build_uefi.sh' first."
    exit 1
fi

# 5. Check Kernel Module
if ! kldstat -n vmm > /dev/null 2>&1; then
    echo "Loading vmm kernel module..."
    kldload vmm
fi

# ==============================================================================
# Image Preparation (The Bhyve Equivalent of Virtual FAT)
# ==============================================================================

echo "========================================"
echo "Creating FAT32 Disk Image ($DISK_IMG)..."

# 1. Create a blank 64MB file
dd if=/dev/zero of="$DISK_IMG" bs=1M count=64 status=none

# 2. Format as FAT32
# -i: image file
# -F: FAT32
mformat -i "$DISK_IMG" -F ::

# 3. Create UEFI Directory Structure
mmd -i "$DISK_IMG" ::/EFI
mmd -i "$DISK_IMG" ::/EFI/BOOT

# 4. Copy Files
# Rename Activator.efi to BOOTX64.EFI for auto-boot
echo "  -> Installing Activator.efi as /EFI/BOOT/BOOTX64.EFI"
mcopy -i "$DISK_IMG" "$EFI_FILE" ::/EFI/BOOT/BOOTX64.EFI

echo "  -> Installing s4_image.bin as /s4_image.bin"
mcopy -i "$DISK_IMG" "$S4IMG_FILE" ::/s4_image.bin

echo "========================================"
echo "Starting Bhyve VM..."
echo "Console redirected to stdio. Press Ctrl + ~ + . to force quit if stuck."
echo "========================================"

# ==============================================================================
# Bhyve Execution
# ==============================================================================

# Cleanup any previous instance
bhyvectl --destroy --vm="$VM_NAME" > /dev/null 2>&1 || true

# Run Bhyve
# -c 1        : 1 vCPU
# -m 512M     : 512MB RAM
# -H          : Yield CPU on HLT (better for host performance)
# -l bootrom  : Load the UEFI Firmware
# -l com1,stdio : CONNECT SERIAL PORT TO TERMINAL
# -s 0,hostbridge : Standard host bridge
# -s 3,ahci-hd : Attach our disk image as a SATA drive
# -s 31,lpc   : ISA bridge (needed for COM port to work)

bhyve \
    -c 1 \
    -m 512M \
    -H \
    -l bootrom,"$BHYVE_FW" \
    -l com1,stdio \
    -s 0,hostbridge \
    -s 3,ahci-hd,"$DISK_IMG" \
    -s 31,lpc \
    "$VM_NAME"

# Cleanup after exit
bhyvectl --destroy --vm="$VM_NAME" > /dev/null 2>&1
echo "VM Terminated."