#!/bin/bash

# ==============================================================================
# Configuration
# ==============================================================================

# Arch Linux standard paths for UEFI Firmware (OVMF)
# Note: Arch now uses 4MB images by default (.4m.fd)
OVMF_CODE="/usr/share/edk2/x64/OVMF_CODE.4m.fd"
OVMF_VARS="/usr/share/edk2/x64/OVMF_VARS.4m.fd"

# S4 image generated by generator/main.py
S4IMG_FILE="./bin/s4_image.bin"

# The target UEFI application built by 'build_uefi.sh'
EFI_FILE="./bin/Activator.efi"

# Temporary directory to simulate the EFI System Partition (ESP)
ESP_DIR="./bin/esp"

# ==============================================================================
# Pre-flight Checks
# ==============================================================================

if [ ! -f "$S4IMG_FILE" ]; then
    echo "Error: Binary not found at $S4IMG_FILE"
    echo "Please run 'python3 generator/main.py' first."
    exit 1
fi

if [ ! -f "$EFI_FILE" ]; then
    echo "Error: Binary not found at $EFI_FILE"
    echo "Please run './scripts/build_uefi.sh' first."
    exit 1
fi

if [ ! -f "$OVMF_CODE" ]; then
    echo "Error: OVMF firmware not found at $OVMF_CODE"
    echo "Please install 'edk2-ovmf' via pacman."
    exit 1
fi

# ==============================================================================
# ESP Setup
# ==============================================================================

# Create the standard UEFI directory structure.
# /EFI/BOOT is the default search path for removable media.
mkdir -p "$ESP_DIR/EFI/BOOT"

# Copy the activator and rename it to BOOTX64.EFI.
# This forces the UEFI firmware to load it automatically on boot
# without needing a boot manager entry.
cp "$EFI_FILE" "$ESP_DIR/EFI/BOOT/BOOTX64.EFI"

# Copy the S4 image to the EFI system partition
cp "$S4IMG_FILE" "$ESP_DIR/s4_image.bin"

echo "========================================"
echo "Preparing Virtual EFI System Partition at $ESP_DIR"
echo "Activator installed as /EFI/BOOT/BOOTX64.EFI"
echo "S4 image installed as /s4_image.bin"
echo "Starting QEMU..."
echo "========================================"

# ==============================================================================
# QEMU Execution
# ==============================================================================

# Explanation of flags:
# -enable-kvm : Use hardware virtualization (faster)
# -m 512M     : Allocate 512MB RAM
# -drive ...  : Load the OVMF firmware code and variables via pflash
#               (readonly=on for vars to prevent QEMU from trying to write back to /usr/share)
# -drive ...  : Mount the $ESP_DIR directory as a virtual FAT32 USB drive
# -net none   : Disable networking to reduce noise
# -nographic  : Optional flag. If enabled, output goes to terminal.
#               For now, we use the GUI window to see the TianoCore logo.

qemu-system-x86_64 \
    -enable-kvm \
    -m 512M \
    -drive if=pflash,format=raw,readonly=on,file="$OVMF_CODE" \
    -drive if=pflash,format=raw,readonly=on,file="$OVMF_VARS" \
    -drive format=raw,file=fat:rw:"$ESP_DIR" \
    -net none